#!/usr/bin/env python3
"""
Export .bin from model structure txt — ZERO guessing.

Reads the structure txt (generated by parse_model_structure.py), loads actual
weight values from safetensors, and writes the .bin file with deterministic layout.

Usage:
    # Step 1: Parse the model structure
    python3 tools/parse_model_structure.py /path/to/hf_model

    # Step 2: Export .bin
    python3 tools/export_from_structure.py /path/to/hf_model --output model.bin
"""

import json
import math
import os
import struct
import sys
from collections import OrderedDict
from pathlib import Path

import numpy as np
import torch


# ============================================================
# Structure txt parser
# ============================================================

def parse_structure_txt(txt_path: str) -> dict:
    """Parse model_structure.txt into a dict. No guessing — pure parsing."""
    config = OrderedDict()
    flags = OrderedDict()
    export_order = []
    tensor_shapes = OrderedDict()

    current_section = None

    with open(txt_path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue

            if line.startswith("[") and line.endswith("]"):
                current_section = line[1:-1]
                continue

            if current_section == "config":
                key, val = parse_kv(line)
                config[key] = val
            elif current_section == "flags":
                key, val = parse_kv(line)
                flags[key] = bool(val)  # parse_kv already returns correct type
            elif current_section == "export_order":
                # format: "tensor_name | [shape]" or "# __rope_cos__ ..."
                if " | " in line:
                    name, shape_str = line.split(" | ", 1)
                    export_order.append(name)
                    # Parse shape for verification
                    shape = eval(shape_str)  # safe: auto-generated
                    tensor_shapes[name] = shape
                elif line.startswith("# __rope"):
                    # Special entries
                    name = line.split()[1]
                    export_order.append(name)

    structure = OrderedDict({
        "config": config,
        "flags": flags,
        "export_order": export_order,
        "tensor_shapes": tensor_shapes,
    })

    return structure


def parse_kv(line: str):
    """Parse 'key = value' line. Value can be int, float, bool, or string."""
    key, val = line.split("=", 1)
    key = key.strip()
    val = val.strip()
    # Try typed parsing
    if val in ("true", "false"):
        return key, val == "true"
    try:
        return key, int(val)
    except ValueError:
        pass
    try:
        return key, float(val)
    except ValueError:
        pass
    return key, val


# ============================================================
# Weight loading
# ============================================================

def load_safetensors_weights(model_path: str, tensor_names: list) -> dict:
    """Load ONLY the needed tensors from safetensors, in fp32."""
    safetensors_path = os.path.join(model_path, "model.safetensors")

    if not os.path.isfile(safetensors_path):
        # Try sharded model
        index_path = os.path.join(model_path, "model.safetensors.index.json")
        if os.path.isfile(index_path):
            return _load_sharded_weights(model_path, tensor_names)
        raise FileNotFoundError(f"No safetensors at {model_path}")

    return _load_single_safetensors(safetensors_path, tensor_names)


def _load_single_safetensors(path: str, tensor_names: list) -> dict:
    """Load tensors from a single safetensors file."""
    with open(path, "rb") as f:
        header_size = struct.unpack("<Q", f.read(8))[0]
        header = json.loads(f.read(header_size))

    weights = {}
    with open(path, "rb") as f:
        data_start = 8 + header_size
        for name in tensor_names:
            if name not in header:
                raise KeyError(f"Tensor {name} not found in safetensors. Available: {sorted(header.keys())[:10]}...")
            meta = header[name]
            offset = meta["data_offsets"][0]
            dtype_str = meta["dtype"]
            shape = meta["shape"]

            f.seek(data_start + offset)
            raw = f.read(meta["data_offsets"][1] - meta["data_offsets"][0])

            tensor = _decode_tensor(raw, dtype_str, shape)
            weights[name] = tensor

    return weights


def _load_sharded_weights(model_path: str, tensor_names: list) -> dict:
    """Load tensors from sharded safetensors."""
    index_path = os.path.join(model_path, "model.safetensors.index.json")
    with open(index_path) as f:
        index = json.load(f)

    weight_map = index["weight_map"]
    shard_files = set(weight_map.values())

    # Group tensors by shard
    shard_to_tensors = {}
    for name in tensor_names:
        shard = weight_map.get(name)
        if shard is None:
            raise KeyError(f"Tensor {name} not found in weight map")
        shard_to_tensors.setdefault(shard, []).append(name)

    all_weights = {}
    for shard_file in sorted(shard_files):
        shard_path = os.path.join(model_path, shard_file)
        needed = shard_to_tensors.get(shard_file, [])
        if not needed:
            continue
        shard_weights = _load_single_safetensors(shard_path, needed)
        all_weights.update(shard_weights)

    return all_weights


def _decode_tensor(raw: bytes, dtype_str: str, shape: list):
    """Decode raw bytes to fp32 torch tensor."""
    dtype_map = {
        "F32": np.float32,
        "F16": np.float16,
        "BF16": np.uint16,  # bfloat16 needs special handling
        "F64": np.float64,
        "I32": np.int32,
        "I64": np.int64,
        "I8": np.int8,
        "U8": np.uint8,
        "BOOL": np.bool_,
    }
    np_dtype = dtype_map.get(dtype_str)
    if np_dtype is None:
        raise ValueError(f"Unknown dtype: {dtype_str}")

    arr = np.frombuffer(raw, dtype=np_dtype).reshape(shape)

    # Handle bfloat16: stored as uint16, interpret as bf16 → float32
    if dtype_str == "BF16":
        arr_uint16 = arr.astype(np.uint16)
        arr_fp32 = np.zeros(arr_uint16.shape, dtype=np.float32)
        # bf16: shift uint16 left by 16 to get float32 bits
        fp32_view = (arr_uint16.astype(np.uint32)) << 16
        arr_fp32 = fp32_view.view(np.float32)
        return torch.from_numpy(arr_fp32).float()

    return torch.from_numpy(arr.astype(np.float32)).float()


# ============================================================
# .bin export
# ============================================================

# Header flags (matches C++ ModelConfigFlags)
FLAG_HAS_QKV_BIAS = 1 << 0
FLAG_HAS_QK_NORM  = 1 << 1
FLAG_HAS_O_BIAS   = 1 << 2
FLAG_HAS_MLP_BIAS = 1 << 3
FLAG_TIED_WEIGHTS = 1 << 4  # if set, lm_head shares embedding weight


def encode_flags(flags_dict: dict, config_dict: dict) -> int:
    """Encode flags into a single int32 bitfield."""
    val = 0
    if flags_dict.get("has_qkv_bias", False):
        val |= FLAG_HAS_QKV_BIAS
    if flags_dict.get("has_qk_norm", False):
        val |= FLAG_HAS_QK_NORM
    if flags_dict.get("has_o_bias", False):
        val |= FLAG_HAS_O_BIAS
    if flags_dict.get("has_mlp_bias", False):
        val |= FLAG_HAS_MLP_BIAS
    if config_dict.get("tie_word_embeddings", True):
        val |= FLAG_TIED_WEIGHTS
    return val


def serialize_fp32(fileobj, tensor: torch.Tensor):
    """Write one fp32 tensor to file."""
    d = tensor.detach().cpu().to(torch.float32).numpy().ravel()
    fileobj.write(struct.pack(f"{len(d)}f", *d))


def compute_rope_cache(head_size: int, max_seq_len: int, theta: float):
    """
    Compute RoPE cos/sin cache, LLaMA-style (half-rotate convention).

    Matches precompute_freqs_cis in model_qwen3.py:
      inv_freq = 1.0 / (theta ** (arange(0, dim, 2)[:dim//2] / dim))
      emb = cat((freqs, freqs), dim=-1)  # [seq_len, head_dim]
    """
    cos_cache = torch.zeros(max_seq_len, head_size, dtype=torch.float32)
    sin_cache = torch.zeros(max_seq_len, head_size, dtype=torch.float32)

    for pos in range(max_seq_len):
        for i in range(head_size):
            pair_idx = i % (head_size // 2)
            freq = 1.0 / (theta ** (2.0 * pair_idx / head_size))
            val = pos * freq
            cos_cache[pos, i] = math.cos(val)
            sin_cache[pos, i] = math.sin(val)

    return cos_cache, sin_cache


def export_bin(structure: dict, weights: dict, output_path: str):
    """Write .bin file deterministically from structure + weights."""
    config = structure["config"]
    flags = structure["flags"]
    export_order = structure["export_order"]

    head_size = config["head_dim"]
    max_seq_len = config["max_position_embeddings"]
    rope_theta = config["rope_theta"]
    vocab_size = config["vocab_size"]
    tied_embeddings = config["tie_word_embeddings"]

    # Legacy format: positive vocab_size = tied, negative = separate
    legacy_vocab_size = vocab_size if tied_embeddings else -vocab_size

    with open(output_path, "wb") as f:
        # Header: 8 x int32 = 32 bytes
        header = struct.pack(
            "iiiiiiii",
            config["hidden_size"],           # dim
            config["intermediate_size"],     # hidden_dim
            config["num_layers"],            # layer_num
            config["num_attention_heads"],   # head_num
            config["num_key_value_heads"],   # kv_head_num
            legacy_vocab_size,               # vocab_size (negative = untied)
            max_seq_len,                     # seq_len
            head_size,                       # head_dim
        )
        f.write(header)

        # Flags: 1 x int32 = 4 bytes (NEW — eliminates all C++ heuristics)
        flags_val = encode_flags(flags, config)
        f.write(struct.pack("i", flags_val))
        print(f"  Flags: 0x{flags_val:08x} (qkv_bias={flags['has_qkv_bias']}, "
              f"qk_norm={flags['has_qk_norm']}, tied={tied_embeddings})")

        # Weights in EXACT export_order sequence
        rope_cache = None
        tensor_count = 0
        for name in export_order:
            if name == "__rope_cos__":
                if rope_cache is None:
                    cos, sin = compute_rope_cache(head_size, max_seq_len, rope_theta)
                    rope_cache = (cos, sin)
                serialize_fp32(f, rope_cache[0])
                tensor_count += 1
            elif name == "__rope_sin__":
                serialize_fp32(f, rope_cache[1])
                tensor_count += 1
            else:
                tensor = weights[name]
                serialize_fp32(f, tensor)
                tensor_count += 1

            if tensor_count % 50 == 0:
                print(f"  Written {tensor_count}/{len(export_order)} entries...", end="\r")

        print(f"  Written {tensor_count}/{len(export_order)} entries. Done.")

    file_size = os.path.getsize(output_path)
    print(f"Output: {output_path} ({file_size / (1024**3):.2f} GB)")


# ============================================================
# Main
# ============================================================

def main():
    import argparse
    parser = argparse.ArgumentParser(
        description="Export .bin from model structure txt — ZERO guessing"
    )
    parser.add_argument("model_path", help="Path to HF model directory")
    parser.add_argument("--structure", "-s", default=None,
                        help="Path to model_structure.txt (default: <model_path>/model_structure.txt)")
    parser.add_argument("--output", "-o", required=True,
                        help="Output .bin file path")
    parser.add_argument("--dtype", default="fp32",
                        help="Export dtype (fp32 only for now)")
    args = parser.parse_args()

    model_path = args.model_path
    structure_path = args.structure or os.path.join(model_path, "model_structure.txt")

    # Step 1: Parse structure
    if not os.path.isfile(structure_path):
        print(f"ERROR: Structure file not found: {structure_path}")
        print("Run parse_model_structure.py first:")
        print(f"  python3 tools/parse_model_structure.py {model_path}")
        sys.exit(1)

    print(f"Reading structure: {structure_path}")
    structure = parse_structure_txt(structure_path)

    print(f"  Model: {structure['config']['model_type']}")
    print(f"  Layers: {structure['config']['num_layers']}, "
          f"Hidden: {structure['config']['hidden_size']}")
    print(f"  Flags: {dict(structure['flags'])}")

    # Step 2: Load weights
    print(f"\nLoading weights from: {model_path}")
    tensor_names = [n for n in structure["export_order"]
                    if n not in ("__rope_cos__", "__rope_sin__")]

    print(f"  Need {len(tensor_names)} tensors")
    weights = load_safetensors_weights(model_path, tensor_names)

    # Verify shapes
    for name in tensor_names:
        expected_shape = structure["tensor_shapes"].get(name)
        if expected_shape is not None:
            actual_shape = list(weights[name].shape)
            if actual_shape != expected_shape:
                raise ValueError(
                    f"Shape mismatch for {name}: "
                    f"expected {expected_shape}, got {actual_shape}"
                )
    print(f"  All {len(weights)} tensors loaded and verified")

    # Step 3: Export
    print(f"\nExporting .bin to: {args.output}")
    export_bin(structure, weights, args.output)


if __name__ == "__main__":
    main()
